// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#ifndef _UI_COMP_FREQLABEL_H
#define _UI_COMP_FREQLABEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT freqLabel
#define UI_COMP_FREQLABEL_FREQLABEL 0
#define _UI_COMP_FREQLABEL_NUM 1
lv_obj_t * ui_freqLabel_create(lv_obj_t * comp_parent);
void ui_event_comp_freqLabel_freqLabel(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
