// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq

#include "../ui.h"

void ui_comp_freqLabel_create_hook(lv_obj_t * comp)
{
}
