// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#include "../ui.h"


void ui_event_comp_freqLabel_freqLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_freqLabel = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(comp_freqLabel[UI_COMP_FREQLABEL_FREQLABEL], target, "", "");
    }
}

// COMPONENT freqLabel

lv_obj_t * ui_freqLabel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_freqLabel;
    cui_freqLabel = lv_label_create(comp_parent);
    lv_obj_set_width(cui_freqLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_freqLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_freqLabel, -30);
    lv_obj_set_y(cui_freqLabel, 0);
    lv_obj_set_align(cui_freqLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_freqLabel, "freq");
    lv_obj_set_style_text_color(cui_freqLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_freqLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_FREQLABEL_NUM);
    children[UI_COMP_FREQLABEL_FREQLABEL] = cui_freqLabel;
    lv_obj_add_event_cb(cui_freqLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_freqLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_freqLabel, ui_event_comp_freqLabel_freqLabel, LV_EVENT_ALL, children);
    ui_comp_freqLabel_create_hook(cui_freqLabel);
    return cui_freqLabel;
}

