// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#ifndef _MASHINA_SQ_FN_GEN_SCREEN_ALMOST_WORK_UI_COMP_HOOK_H
#define _MASHINA_SQ_FN_GEN_SCREEN_ALMOST_WORK_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_freqLabel_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
