.TH "_button_config_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_button_config_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBpin\fP"
.br
.ti -1c
.RI "bool \fBb_is_active_on_high_level\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool b_is_active_on_high_level"

.SS "uint8_t pin"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
