.TH "_fn_generator_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_fn_generator_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include </home/mbakmaz/bytelab2024/final_task/mashina/components/function_generator/fn_gen\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfn_signal_config_t\fP \fB_config\fP"
.br
.ti -1c
.RI "int \fB_raw_val\fP [\fBFN_GEN_POINT_ARR_LEN\fP]"
.br
.ti -1c
.RI "int \fB_volt_val\fP [\fBFN_GEN_POINT_ARR_LEN\fP]"
.br
.ti -1c
.RI "int \fB_period_index\fP"
.br
.ti -1c
.RI "bool \fB_is_running\fP"
.br
.ti -1c
.RI "\fBfn_signal_config_t\fP \fBpresets\fP [\fBFN_GEN_PRESET_NUMBER\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBfn_signal_config_t\fP _config"

.SS "bool _is_running"

.SS "int _period_index"

.SS "int _raw_val[\fBFN_GEN_POINT_ARR_LEN\fP]"

.SS "int _volt_val[\fBFN_GEN_POINT_ARR_LEN\fP]"

.SS "\fBfn_signal_config_t\fP presets[\fBFN_GEN_PRESET_NUMBER\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
