.TH "_fn_signal_config_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_fn_signal_config_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include </home/mbakmaz/bytelab2024/final_task/mashina/components/function_generator/fn_gen\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfn_signal_type_t\fP \fBsignal\fP"
.br
.ti -1c
.RI "int \fBfrequency_Hz\fP"
.br
.ti -1c
.RI "int \fBamplitude_mV\fP"
.br
.ti -1c
.RI "int \fBduty_cycle_percentage\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int amplitude_mV"

.SS "int duty_cycle_percentage"

.SS "int frequency_Hz"

.SS "\fBfn_signal_type_t\fP signal"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
