.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/joystick Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/joystick Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjoystick\&.c\fP"
.br
.RI "This file implements Joystick as two potentiometers\&. "
.ti -1c
.RI "file \fBjoystick\&.h\fP"
.br
.RI "See the source file\&. "
.in -1c
