.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/temp_sensor_sht31 Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/temp_sensor_sht31 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtemp_sensor_sht31\&.c\fP"
.br
.RI "Driver for the SHT31 temperature and humidity sensor using I2C protocol\&. "
.ti -1c
.RI "file \fBtemp_sensor_sht31\&.h\fP"
.br
.RI "See the source file\&. "
.in -1c
