.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/oscilloscope Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/oscilloscope Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBplatform\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBoscilloscope\&.c\fP"
.br
.RI "Class to capture signals from ADC\&. "
.ti -1c
.RI "file \fBoscilloscope\&.h\fP"
.br
.RI "See the source file\&. "
.in -1c
