.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBui_comp\&.c\fP"
.br
.ti -1c
.RI "file \fBui_comp\&.h\fP"
.br
.ti -1c
.RI "file \fBui_comp_freqlabel\&.c\fP"
.br
.ti -1c
.RI "file \fBui_comp_freqlabel\&.h\fP"
.br
.ti -1c
.RI "file \fBui_comp_hook\&.c\fP"
.br
.ti -1c
.RI "file \fBui_comp_hook\&.h\fP"
.br
.in -1c
