.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/potentiometer Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/potentiometer Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpotentiometer\&.c\fP"
.br
.RI "THe file implements behaviour of potentiometer\&. "
.ti -1c
.RI "file \fBpotentiometer\&.h\fP"
.br
.RI "See the source file\&. "
.in -1c
