.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/button/platform/inc Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/button/platform/inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbutton_gpio\&.h\fP"
.br
.RI "See the source file\&. "
.in -1c
