.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/button Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/button Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBplatform\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbutton\&.c\fP"
.br
.RI "Button implementation for Byte Lab Development Kit\&. "
.ti -1c
.RI "file \fBbutton\&.h\fP"
.br
.RI "See the source file\&. "
.in -1c
