.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/images Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/images Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBui_img_1091903730\&.c\fP"
.br
.ti -1c
.RI "file \fBui_img_1501662095\&.c\fP"
.br
.ti -1c
.RI "file \fBui_img_653708034\&.c\fP"
.br
.ti -1c
.RI "file \fBui_img_bl_logo_light_png\&.c\fP"
.br
.ti -1c
.RI "file \fBui_img_bl_logo_symbol_png\&.c\fP"
.br
.ti -1c
.RI "file \fBui_img_humidity_15px_png\&.c\fP"
.br
.ti -1c
.RI "file \fBui_img_temp_15px_png\&.c\fP"
.br
.ti -1c
.RI "file \fBui_img_wifi_iconmini_png\&.c\fP"
.br
.in -1c
