.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/screens Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/screens Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBui_functiongenscr\&.c\fP"
.br
.ti -1c
.RI "file \fBui_homescr\&.c\fP"
.br
.ti -1c
.RI "file \fBui_oscilloscopescr\&.c\fP"
.br
.in -1c
