.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/osc_chart Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/osc_chart Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBosc_chart\&.c\fP"
.br
.RI "Class to handle lvgl chart used as oscilloscope\&. "
.ti -1c
.RI "file \fBosc_chart\&.h\fP"
.br
.RI "See the source file\&. "
.in -1c
