.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/function_generator/platform/src Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/function_generator/platform/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdac\&.c\fP"
.br
.RI "COPYRIGHT NOTICE: (c) 2024 Byte Lab Grupa d\&.o\&.o\&. All rights reserved\&. "
.ti -1c
.RI "file \fBtimer\&.c\fP"
.br
.RI "GP timer wrapper class\&. "
.in -1c
