.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/led/platform/src Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/led/platform/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBled_gpio\&.c\fP"
.br
.RI "Platform implementation od LED driver\&. "
.in -1c
