.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app Directory Reference" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBosc_chart\fP"
.br
.ti -1c
.RI "directory \fBsquareline\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgui\&.c\fP"
.br
.RI "This file is an example for how to use the LVGL library\&. "
.ti -1c
.RI "file \fBgui\&.h\fP"
.br
.RI "See the source file\&. "
.ti -1c
.RI "file \fBui_app\&.c\fP"
.br
.RI "System init\&. "
.ti -1c
.RI "file \fBui_app\&.h\fP"
.br
.RI "See the source file\&. "
.in -1c
