.TH "_joystick_config_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_joystick_config_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBpin_x\fP"
.br
.ti -1c
.RI "uint8_t \fBchan_x\fP"
.br
.ti -1c
.RI "uint8_t \fBpin_y\fP"
.br
.ti -1c
.RI "uint8_t \fBchan_y\fP"
.br
.ti -1c
.RI "uint16_t \fBmax_voltage_mv\fP"
.br
.ti -1c
.RI "bool \fBb_is_reversed_x\fP"
.br
.ti -1c
.RI "bool \fBb_is_reversed_y\fP"
.br
.ti -1c
.RI "\fBpotentiometer_t\fP * \fBp_pot_x\fP"
.br
.ti -1c
.RI "\fBpotentiometer_t\fP * \fBp_pot_y\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool b_is_reversed_x"

.SS "bool b_is_reversed_y"

.SS "uint8_t chan_x"

.SS "uint8_t chan_y"

.SS "uint16_t max_voltage_mv"

.SS "\fBpotentiometer_t\fP* p_pot_x"

.SS "\fBpotentiometer_t\fP* p_pot_y"

.SS "uint8_t pin_x"

.SS "uint8_t pin_y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
