.TH "_led_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_led_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBled_gpio_t\fP * \fBp_led_gpio\fP"
.br
.ti -1c
.RI "\fBled_pattern_t\fP \fBpattern\fP"
.br
.ti -1c
.RI "\fBled_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "uint32_t \fBtime_since_state_change_ms\fP"
.br
.ti -1c
.RI "uint32_t \fBtime_since_pattern_change_ms\fP"
.br
.ti -1c
.RI "uint32_t \fBtimeout_ms\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBled_gpio_t\fP* p_led_gpio"

.SS "\fBled_pattern_t\fP pattern"

.SS "\fBled_state_t\fP state"

.SS "uint32_t time_since_pattern_change_ms"

.SS "uint32_t time_since_state_change_ms"

.SS "uint32_t timeout_ms"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
