.TH "_osc_timer_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_osc_timer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtimer_callback\fP \fB_cb\fP"
.br
.ti -1c
.RI "int \fB_period_uc\fP"
.br
.ti -1c
.RI "esp_timer_handle_t \fB_periodic_timer\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBtimer_callback\fP _cb"

.SS "int _period_uc"

.SS "esp_timer_handle_t _periodic_timer"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
