.TH "_potentiometer_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_potentiometer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBpin\fP"
.br
.ti -1c
.RI "bool \fBb_is_reversed\fP"
.br
.ti -1c
.RI "uint8_t \fBchannel\fP"
.br
.ti -1c
.RI "uint16_t \fBmax_voltage_mv\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool b_is_reversed"

.SS "uint8_t channel"

.SS "uint16_t max_voltage_mv"

.SS "uint8_t pin"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
