.TH "_ui_anim_user_data_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ui_anim_user_data_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include </home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/ui_helpers\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "lv_obj_t * \fBtarget\fP"
.br
.ti -1c
.RI "lv_img_dsc_t ** \fBimgset\fP"
.br
.ti -1c
.RI "int32_t \fBimgset_size\fP"
.br
.ti -1c
.RI "int32_t \fBval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes an animation 
.SH "Field Documentation"
.PP 
.SS "lv_img_dsc_t** imgset"

.SS "int32_t imgset_size"

.SS "lv_obj_t* target"

.SS "int32_t val"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
