.TH "/home/mbakmaz/bytelab2024/final_task/mashina/main/app_main.c" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/main/app_main.c
.SH SYNOPSIS
.br
.PP
\fR#include 'ui_app/gui\&.h'\fP
.br
\fR#include 'ui_app/ui_app\&.h'\fP
.br
\fR#include 'fn_gen\&.h'\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include 'freertos/FreeRTOS\&.h'\fP
.br
\fR#include 'freertos/task\&.h'\fP
.br
\fR#include 'esp_freertos_hooks\&.h'\fP
.br
\fR#include 'freertos/semphr\&.h'\fP
.br
\fR#include 'esp_log\&.h'\fP
.br
\fR#include 'esp_timer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapp_main\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void app_main (void )"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
