.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/function_generator/platform/inc/dac.h" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/function_generator/platform/inc/dac.h \- See the source file\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'driver/dac\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBESP_DAC_CHAN\fP   DAC_CHANNEL_1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdac_init\fP (void)"
.br
.RI "Enables esp DAC peripheral\&. "
.ti -1c
.RI "void \fBdac_output\fP (uint8_t dac_value)"
.br
.RI "Outputs 8 bit value to DAC\&. "
.in -1c
.SH "Detailed Description"
.PP 
See the source file\&. 

COPYRIGHT NOTICE: (c) 2024 Byte Lab Grupa d\&.o\&.o\&. All rights reserved\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define ESP_DAC_CHAN   DAC_CHANNEL_1"

.SH "Function Documentation"
.PP 
.SS "void dac_init (void )"

.PP
Enables esp DAC peripheral\&. 
.SS "void dac_output (uint8_t dac_value)"

.PP
Outputs 8 bit value to DAC\&. 
.PP
\fBParameters\fP
.RS 4
\fIdac_value\fP 8 bit value 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
