.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/gui.h" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/gui.h \- See the source file\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'joystick\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgui_init\fP (void)"
.br
.RI "Initializes LVGL, TFT drivers and input drivers and starts task needed for GUI operation\&. "
.ti -1c
.RI "void \fBgui_receive_joystick_pos\fP (int pos)"
.br
.in -1c
.SH "Detailed Description"
.PP 
See the source file\&. 

COPYRIGHT NOTICE: (c) 2022 Byte Lab Grupa d\&.o\&.o\&. All rights reserved\&. 
.SH "Function Documentation"
.PP 
.SS "void gui_init (void )"

.PP
Initializes LVGL, TFT drivers and input drivers and starts task needed for GUI operation\&. 
.SS "void gui_receive_joystick_pos (int pos)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
