.TH "joystick_position_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joystick_position_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include </home/mbakmaz/bytelab2024/final_task/mashina/components/joystick/joystick\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBposition_x\fP"
.br
.ti -1c
.RI "uint32_t \fBposition_y\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t position_x"

.SS "uint32_t position_y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
