.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/led/led.h" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/led/led.h \- See the source file\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include 'led_gpio\&.h'\fP
.br
\fR#include <limits\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNO_TIMEOUT\fP   (UINT_MAX)"
.br
.ti -1c
.RI "#define \fBLED_SLOWBLINK_HALF_PERIOD_MS\fP   (1000U)"
.br
.ti -1c
.RI "#define \fBLED_FASTBLINK_HALF_PERIOD_MS\fP   (100U)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_led_t\fP \fBled_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBled_pattern_t\fP { \fBLED_PATTERN_NONE\fP, \fBLED_PATTERN_KEEP_ON\fP, \fBLED_PATTERN_SLOWBLINK\fP, \fBLED_PATTERN_FASTBLINK\fP, \fBLED_PATTERN_COUNT\fP }"
.br
.ti -1c
.RI "enum \fBled_name_t\fP { \fBLED_RED\fP, \fBLED_GREEN\fP, \fBLED_BLUE\fP, \fBLED_COUNT\fP }"
.br
.ti -1c
.RI "enum \fBled_err_t\fP { \fBLED_ERR_NONE\fP = 0, \fBLED_ERR_CREATE\fP = -1, \fBLED_ERR_INVALID_PATTERN\fP = -2, \fBLED_ERR_INVALID_LED\fP = -3, \fBLED_ERR_MUTEX_FAIL\fP = -4 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBled_err_t\fP \fBled_create\fP (\fBled_name_t\fP led)"
.br
.RI "Create LED driver and configure all needed functionalities\&. "
.ti -1c
.RI "\fBled_err_t\fP \fBled_pattern_run\fP (\fBled_name_t\fP led, \fBled_pattern_t\fP led_pattern, uint32_t timeout_ms)"
.br
.RI "Set led pattern\&. Don't call this function from ISR\&. "
.ti -1c
.RI "\fBled_err_t\fP \fBled_pattern_reset\fP (\fBled_name_t\fP led)"
.br
.RI "Reset LED pattern\&. "
.in -1c
.SH "Detailed Description"
.PP 
See the source file\&. 


.PP
\fB\fP
.RS 4

.RE
.PP
COPYRIGHT NOTICE: (c) 2022 Byte Lab Grupa d\&.o\&.o\&. All rights reserved\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define LED_FASTBLINK_HALF_PERIOD_MS   (100U)"

.SS "#define LED_SLOWBLINK_HALF_PERIOD_MS   (1000U)"

.SS "#define NO_TIMEOUT   (UINT_MAX)"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_led_t\fP \fBled_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBled_err_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILED_ERR_NONE \fP
.TP
\f(BILED_ERR_CREATE \fP
.TP
\f(BILED_ERR_INVALID_PATTERN \fP
.TP
\f(BILED_ERR_INVALID_LED \fP
.TP
\f(BILED_ERR_MUTEX_FAIL \fP
.SS "enum \fBled_name_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILED_RED \fP
.TP
\f(BILED_GREEN \fP
.TP
\f(BILED_BLUE \fP
.TP
\f(BILED_COUNT \fP
.SS "enum \fBled_pattern_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILED_PATTERN_NONE \fP
.TP
\f(BILED_PATTERN_KEEP_ON \fP
.TP
\f(BILED_PATTERN_SLOWBLINK \fP
.TP
\f(BILED_PATTERN_FASTBLINK \fP
.TP
\f(BILED_PATTERN_COUNT \fP
.SH "Function Documentation"
.PP 
.SS "\fBled_err_t\fP led_create (\fBled_name_t\fP led)"

.PP
Create LED driver and configure all needed functionalities\&. 
.PP
\fBParameters\fP
.RS 4
\fIled\fP - Name of the LED to be created\&.
.RE
.PP
\fBReturns\fP
.RS 4
Status of creation\&. 
.RE
.PP

.SS "\fBled_err_t\fP led_pattern_reset (\fBled_name_t\fP led)"

.PP
Reset LED pattern\&. 
.PP
\fBParameters\fP
.RS 4
\fIled\fP - LED name\&.
.RE
.PP
\fBReturns\fP
.RS 4
Status of pattern reseting\&. 
.RE
.PP

.SS "\fBled_err_t\fP led_pattern_run (\fBled_name_t\fP led, \fBled_pattern_t\fP led_pattern, uint32_t timeout_ms)"

.PP
Set led pattern\&. Don't call this function from ISR\&. 
.PP
\fBParameters\fP
.RS 4
\fIled\fP - LED name\&. 
.br
\fIled_pattern\fP - LED pattern to be run\&. 
.br
\fItimeout_ms\fP - timeout in milliseconds (if 0 run infinitely)\&.
.RE
.PP
\fBReturns\fP
.RS 4
Status of pattern starting\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
