.TH "osc_chart_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osc_chart_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include </home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/osc_chart/osc_chart\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBoscilloscope_t\fP * \fBp_chan_1\fP"
.br
.ti -1c
.RI "\fBoscilloscope_t\fP * \fBp_chan_2\fP"
.br
.ti -1c
.RI "lv_chart_series_t * \fBp_ser1\fP"
.br
.ti -1c
.RI "lv_chart_series_t * \fBp_ser2\fP"
.br
.ti -1c
.RI "int \fBdiv_mV\fP"
.br
.ti -1c
.RI "int \fBdiv_ms\fP"
.br
.ti -1c
.RI "int \fBdata_length\fP"
.br
.ti -1c
.RI "int * \fBdata_1\fP"
.br
.ti -1c
.RI "int * \fBdata_2\fP"
.br
.ti -1c
.RI "lv_obj_t * \fBchart\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "lv_obj_t* chart"

.SS "int* data_1"

.SS "int* data_2"

.SS "int data_length"

.SS "int div_ms"

.SS "int div_mV"

.SS "\fBoscilloscope_t\fP* p_chan_1"

.SS "\fBoscilloscope_t\fP* p_chan_2"

.SS "lv_chart_series_t* p_ser1"

.SS "lv_chart_series_t* p_ser2"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
