.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/ui_app.h" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/ui_app.h \- See the source file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapp_start\fP (void)"
.br
.RI "Starts application\&. "
.ti -1c
.RI "void \fBui_turn_off_oscilloscope\fP (void)"
.br
.RI "Turns off adc reading while function generator is active\&. "
.ti -1c
.RI "void \fBui_turn_on_oscilloscope\fP (void)"
.br
.RI "Turns adc back on while function generator stops\&. "
.in -1c
.SH "Detailed Description"
.PP 
See the source file\&. 

COPYRIGHT NOTICE: (c) 2024 Byte Lab Grupa d\&.o\&.o\&. All rights reserved\&. 
.SH "Function Documentation"
.PP 
.SS "void app_start (void )"

.PP
Starts application\&. 
.SS "void ui_turn_off_oscilloscope (void )"

.PP
Turns off adc reading while function generator is active\&. 
.SS "void ui_turn_on_oscilloscope (void )"

.PP
Turns adc back on while function generator stops\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
