.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components/ui_comp_hook.h" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components/ui_comp_hook.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBui_comp_freqLabel_create_hook\fP (lv_obj_t *comp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ui_comp_freqLabel_create_hook (lv_obj_t * comp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
