.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components/ui_comp_freqlabel.h" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components/ui_comp_freqlabel.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ui\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUI_COMP_FREQLABEL_FREQLABEL\fP   0"
.br
.ti -1c
.RI "#define \fB_UI_COMP_FREQLABEL_NUM\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "lv_obj_t * \fBui_freqLabel_create\fP (lv_obj_t *comp_parent)"
.br
.ti -1c
.RI "void \fBui_event_comp_freqLabel_freqLabel\fP (lv_event_t *e)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _UI_COMP_FREQLABEL_NUM   1"

.SS "#define UI_COMP_FREQLABEL_FREQLABEL   0"

.SH "Function Documentation"
.PP 
.SS "void ui_event_comp_freqLabel_freqLabel (lv_event_t * e)"

.SS "lv_obj_t * ui_freqLabel_create (lv_obj_t * comp_parent)"
1

.PP
1
.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
