.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components/ui_comp_freqlabel.c" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components/ui_comp_freqlabel.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ui\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBui_event_comp_freqLabel_freqLabel\fP (lv_event_t *e)"
.br
.ti -1c
.RI "lv_obj_t * \fBui_freqLabel_create\fP (lv_obj_t *comp_parent)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ui_event_comp_freqLabel_freqLabel (lv_event_t * e)"

.SS "lv_obj_t * ui_freqLabel_create (lv_obj_t * comp_parent)"
1

.PP
1
.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
