.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components/ui_comp.h" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/components/ui_comp.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ui\&.h'\fP
.br
\fR#include 'ui_comp_freqlabel\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBget_component_child_event_cb\fP (lv_event_t *e)"
.br
.ti -1c
.RI "void \fBdel_component_child_event_cb\fP (lv_event_t *e)"
.br
.ti -1c
.RI "lv_obj_t * \fBui_comp_get_child\fP (lv_obj_t *comp, uint32_t child_idx)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBLV_EVENT_GET_COMP_CHILD\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void del_component_child_event_cb (lv_event_t * e)"

.SS "void get_component_child_event_cb (lv_event_t * e)"

.SS "lv_obj_t * ui_comp_get_child (lv_obj_t * comp, uint32_t child_idx)"

.SH "Variable Documentation"
.PP 
.SS "uint32_t LV_EVENT_GET_COMP_CHILD\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
