.TH "ui_comp_get_child_t" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui_comp_get_child_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBchild_idx\fP"
.br
.ti -1c
.RI "lv_obj_t * \fBchild\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "lv_obj_t* child"

.SS "uint32_t child_idx"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
