.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/ui_helpers.c" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/ui_helpers.c
.SH SYNOPSIS
.br
.PP
\fR#include 'ui_helpers\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_ui_bar_set_property\fP (lv_obj_t *target, int id, int val)"
.br
.ti -1c
.RI "void \fB_ui_basic_set_property\fP (lv_obj_t *target, int id, int val)"
.br
.ti -1c
.RI "void \fB_ui_dropdown_set_property\fP (lv_obj_t *target, int id, int val)"
.br
.ti -1c
.RI "void \fB_ui_image_set_property\fP (lv_obj_t *target, int id, uint8_t *val)"
.br
.ti -1c
.RI "void \fB_ui_label_set_property\fP (lv_obj_t *target, int id, const char *val)"
.br
.ti -1c
.RI "void \fB_ui_roller_set_property\fP (lv_obj_t *target, int id, int val)"
.br
.ti -1c
.RI "void \fB_ui_slider_set_property\fP (lv_obj_t *target, int id, int val)"
.br
.ti -1c
.RI "void \fB_ui_screen_change\fP (lv_obj_t **target, lv_scr_load_anim_t fademode, int spd, int delay, void(*target_init)(void))"
.br
.ti -1c
.RI "void \fB_ui_screen_delete\fP (lv_obj_t **target)"
.br
.ti -1c
.RI "void \fB_ui_arc_increment\fP (lv_obj_t *target, int val)"
.br
.ti -1c
.RI "void \fB_ui_bar_increment\fP (lv_obj_t *target, int val, int anm)"
.br
.ti -1c
.RI "void \fB_ui_slider_increment\fP (lv_obj_t *target, int val, int anm)"
.br
.ti -1c
.RI "void \fB_ui_keyboard_set_target\fP (lv_obj_t *keyboard, lv_obj_t *textarea)"
.br
.ti -1c
.RI "void \fB_ui_flag_modify\fP (lv_obj_t *target, int32_t flag, int value)"
.br
.ti -1c
.RI "void \fB_ui_state_modify\fP (lv_obj_t *target, int32_t state, int value)"
.br
.ti -1c
.RI "void \fB_ui_textarea_move_cursor\fP (lv_obj_t *target, int val)"
.br
.ti -1c
.RI "void \fBscr_unloaded_delete_cb\fP (lv_event_t *e)"
.br
.ti -1c
.RI "void \fB_ui_opacity_set\fP (lv_obj_t *target, int val)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_free_user_data\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_set_x\fP (lv_anim_t *a, int32_t v)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_set_y\fP (lv_anim_t *a, int32_t v)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_set_width\fP (lv_anim_t *a, int32_t v)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_set_height\fP (lv_anim_t *a, int32_t v)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_set_opacity\fP (lv_anim_t *a, int32_t v)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_set_image_zoom\fP (lv_anim_t *a, int32_t v)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_set_image_angle\fP (lv_anim_t *a, int32_t v)"
.br
.ti -1c
.RI "void \fB_ui_anim_callback_set_image_frame\fP (lv_anim_t *a, int32_t v)"
.br
.ti -1c
.RI "int32_t \fB_ui_anim_callback_get_x\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "int32_t \fB_ui_anim_callback_get_y\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "int32_t \fB_ui_anim_callback_get_width\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "int32_t \fB_ui_anim_callback_get_height\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "int32_t \fB_ui_anim_callback_get_opacity\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "int32_t \fB_ui_anim_callback_get_image_zoom\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "int32_t \fB_ui_anim_callback_get_image_angle\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "int32_t \fB_ui_anim_callback_get_image_frame\fP (lv_anim_t *a)"
.br
.ti -1c
.RI "void \fB_ui_arc_set_text_value\fP (lv_obj_t *trg, lv_obj_t *src, const char *prefix, const char *postfix)"
.br
.ti -1c
.RI "void \fB_ui_slider_set_text_value\fP (lv_obj_t *trg, lv_obj_t *src, const char *prefix, const char *postfix)"
.br
.ti -1c
.RI "void \fB_ui_checked_set_text_value\fP (lv_obj_t *trg, lv_obj_t *src, const char *txt_on, const char *txt_off)"
.br
.ti -1c
.RI "void \fB_ui_spinbox_step\fP (lv_obj_t *target, int val)"
.br
.ti -1c
.RI "void \fB_ui_switch_theme\fP (int val)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _ui_anim_callback_free_user_data (lv_anim_t * a)"

.SS "int32_t _ui_anim_callback_get_height (lv_anim_t * a)"

.SS "int32_t _ui_anim_callback_get_image_angle (lv_anim_t * a)"

.SS "int32_t _ui_anim_callback_get_image_frame (lv_anim_t * a)"

.SS "int32_t _ui_anim_callback_get_image_zoom (lv_anim_t * a)"

.SS "int32_t _ui_anim_callback_get_opacity (lv_anim_t * a)"

.SS "int32_t _ui_anim_callback_get_width (lv_anim_t * a)"

.SS "int32_t _ui_anim_callback_get_x (lv_anim_t * a)"

.SS "int32_t _ui_anim_callback_get_y (lv_anim_t * a)"

.SS "void _ui_anim_callback_set_height (lv_anim_t * a, int32_t v)"

.SS "void _ui_anim_callback_set_image_angle (lv_anim_t * a, int32_t v)"

.SS "void _ui_anim_callback_set_image_frame (lv_anim_t * a, int32_t v)"

.SS "void _ui_anim_callback_set_image_zoom (lv_anim_t * a, int32_t v)"

.SS "void _ui_anim_callback_set_opacity (lv_anim_t * a, int32_t v)"

.SS "void _ui_anim_callback_set_width (lv_anim_t * a, int32_t v)"

.SS "void _ui_anim_callback_set_x (lv_anim_t * a, int32_t v)"

.SS "void _ui_anim_callback_set_y (lv_anim_t * a, int32_t v)"

.SS "void _ui_arc_increment (lv_obj_t * target, int val)"

.SS "void _ui_arc_set_text_value (lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)"

.SS "void _ui_bar_increment (lv_obj_t * target, int val, int anm)"

.SS "void _ui_bar_set_property (lv_obj_t * target, int id, int val)"

.SS "void _ui_basic_set_property (lv_obj_t * target, int id, int val)"

.SS "void _ui_checked_set_text_value (lv_obj_t * trg, lv_obj_t * src, const char * txt_on, const char * txt_off)"

.SS "void _ui_dropdown_set_property (lv_obj_t * target, int id, int val)"

.SS "void _ui_flag_modify (lv_obj_t * target, int32_t flag, int value)"

.SS "void _ui_image_set_property (lv_obj_t * target, int id, uint8_t * val)"

.SS "void _ui_keyboard_set_target (lv_obj_t * keyboard, lv_obj_t * textarea)"

.SS "void _ui_label_set_property (lv_obj_t * target, int id, const char * val)"

.SS "void _ui_opacity_set (lv_obj_t * target, int val)"

.SS "void _ui_roller_set_property (lv_obj_t * target, int id, int val)"

.SS "void _ui_screen_change (lv_obj_t ** target, lv_scr_load_anim_t fademode, int spd, int delay, void(* target_init )(void))"

.SS "void _ui_screen_delete (lv_obj_t ** target)"

.SS "void _ui_slider_increment (lv_obj_t * target, int val, int anm)"

.SS "void _ui_slider_set_property (lv_obj_t * target, int id, int val)"

.SS "void _ui_slider_set_text_value (lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)"

.SS "void _ui_spinbox_step (lv_obj_t * target, int val)"

.SS "void _ui_state_modify (lv_obj_t * target, int32_t state, int value)"

.SS "void _ui_switch_theme (int val)"

.SS "void _ui_textarea_move_cursor (lv_obj_t * target, int val)"

.SS "void scr_unloaded_delete_cb (lv_event_t * e)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
