.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/images/ui_img_bl_logo_symbol_png.c" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/images/ui_img_bl_logo_symbol_png.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ui\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLV_ATTRIBUTE_MEM_ALIGN\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBLV_ATTRIBUTE_MEM_ALIGN\fP uint8_t \fBui_img_bl_logo_symbol_png_data\fP []"
.br
.ti -1c
.RI "const lv_img_dsc_t \fBui_img_bl_logo_symbol_png\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LV_ATTRIBUTE_MEM_ALIGN"

.SH "Variable Documentation"
.PP 
.SS "const lv_img_dsc_t ui_img_bl_logo_symbol_png"
\fBInitial value:\fP
.nf
= {
    \&.header\&.always_zero = 0,
    \&.header\&.w = 170,
    \&.header\&.h = 170,
    \&.data_size = sizeof(ui_img_bl_logo_symbol_png_data),
    \&.header\&.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    \&.data = ui_img_bl_logo_symbol_png_data
}
.PP
.fi

.SS "const \fBLV_ATTRIBUTE_MEM_ALIGN\fP uint8_t ui_img_bl_logo_symbol_png_data[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
