.TH "/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/screens/ui_oscilloscopescr.c" 3 "Version ." "Mashina" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mbakmaz/bytelab2024/final_task/mashina/components/ui_app/squareline/screens/ui_oscilloscopescr.c
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./ui\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBui_oscilloscopescr_screen_init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ui_oscilloscopescr_screen_init (void )"
Flags

.PP
50

.PP
50

.PP
Flags

.PP
Flags

.PP
Flags

.PP
1

.PP
1

.PP
1

.PP
1

.PP
15

.PP
15

.PP
Flags

.PP
Flags

.PP
15

.PP
15

.PP
Flags

.PP
Flags

.PP
Flags

.PP
Flags

.PP
1

.PP
1

.PP
Flags

.PP
1

.PP
1

.PP
Flags

.PP
1

.PP
1

.PP
Flags

.PP
1

.PP
1

.PP
Flags

.PP
1

.PP
1

.PP
Flags

.PP
1

.PP
1

.PP
1

.PP
1

.PP
1

.PP
1

.PP
States

.PP
Flags

.PP
States

.PP
Flags

.PP
1

.PP
1

.PP
1

.PP
1
.SH "Author"
.PP 
Generated automatically by Doxygen for Mashina from the source code\&.
