// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#include "../ui.h"

void ui_functiongenscr_screen_init(void)
{
    ui_functiongenscr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_functiongenscr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_functiongenscr, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_functiongenscr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_functiongenscr, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_functiongenscr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_functiongenscr, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_functiongenscr);
    lv_img_set_src(ui_Image13, &ui_img_bl_logo_symbol_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 170
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 170
    lv_obj_set_x(ui_Image13, 47);
    lv_obj_set_y(ui_Image13, 12);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_functiongenscr);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -18);
    lv_obj_set_y(ui_Label1, -94);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "FUNCTION GENERATOR");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backBtn2 = lv_btn_create(ui_functiongenscr);
    lv_obj_set_width(ui_backBtn2, 31);
    lv_obj_set_height(ui_backBtn2, 26);
    lv_obj_set_x(ui_backBtn2, -132);
    lv_obj_set_y(ui_backBtn2, -94);
    lv_obj_set_align(ui_backBtn2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_backBtn2, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backBtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_backBtn2, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_backBtn2, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_backBtn2, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Image5 = lv_img_create(ui_backBtn2);
    lv_img_set_src(ui_Image5, &ui_img_653708034);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 100);

    ui_signalTypeDropdown = lv_dropdown_create(ui_functiongenscr);
    lv_dropdown_set_options(ui_signalTypeDropdown, "Sine\nSquare\nTriangle\nSawtooth");
    lv_obj_set_width(ui_signalTypeDropdown, 108);
    lv_obj_set_height(ui_signalTypeDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signalTypeDropdown, -90);
    lv_obj_set_y(ui_signalTypeDropdown, -35);
    lv_obj_set_align(ui_signalTypeDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_signalTypeDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_signalTypeDropdown, lv_color_hex(0xF9F7F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_signalTypeDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_signalTypeDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_signalTypeDropdown, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_signalTypeDropdown, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_signalTypeDropdown, 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_signalTypeDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_signalTypeDropdown, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_signalTypeDropdown, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_signalTypeDropdown, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_text_color(ui_signalTypeDropdown, lv_color_hex(0x202829), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_signalTypeDropdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_signalTypeDropdown), lv_color_hex(0xC2C3C5),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_signalTypeDropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_signalTypeDropdown), lv_color_hex(0x31C294),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_signalTypeDropdown), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_signalTypeLabel = lv_label_create(ui_functiongenscr);
    lv_obj_set_width(ui_signalTypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_signalTypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signalTypeLabel, -112);
    lv_obj_set_y(ui_signalTypeLabel, -63);
    lv_obj_set_align(ui_signalTypeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_signalTypeLabel, "Signal type:");
    lv_obj_set_style_text_color(ui_signalTypeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_signalTypeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_signalTypeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freqarc1 = lv_arc_create(ui_functiongenscr);
    lv_obj_set_width(ui_freqarc1, 150);
    lv_obj_set_height(ui_freqarc1, 90);
    lv_obj_set_x(ui_freqarc1, -67);
    lv_obj_set_y(ui_freqarc1, 52);
    lv_obj_set_align(ui_freqarc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_freqarc1, 50, 1500);
    lv_arc_set_value(ui_freqarc1, 0);

    lv_obj_set_style_arc_color(ui_freqarc1, lv_color_hex(0x31C294), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_freqarc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_freqarc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_freqarc1, 255, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_freqarc1, 2, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_freqarc1, 3, LV_PART_INDICATOR | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_bg_color(ui_freqarc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freqarc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_freqarc1, lv_color_hex(0x31C294), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_freqarc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_freqarc1, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_freqarc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_freqarc1, 255, LV_PART_KNOB | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_freqarc1, 2, LV_PART_KNOB | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_freqarc1, 3, LV_PART_KNOB | LV_STATE_FOCUS_KEY);

    ui_freqLabel1 = lv_label_create(ui_freqarc1);
    lv_obj_set_width(ui_freqLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_freqLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_freqLabel1, -30);
    lv_obj_set_y(ui_freqLabel1, 0);
    lv_obj_set_align(ui_freqLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_freqLabel1, "");
    lv_obj_set_style_text_color(ui_freqLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_freqLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HzLabel = lv_label_create(ui_freqarc1);
    lv_obj_set_width(ui_HzLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HzLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HzLabel, -29);
    lv_obj_set_y(ui_HzLabel, 19);
    lv_obj_set_align(ui_HzLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HzLabel, "Hz");
    lv_obj_set_style_text_color(ui_HzLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HzLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amplArc = lv_arc_create(ui_functiongenscr);
    lv_obj_set_width(ui_amplArc, 150);
    lv_obj_set_height(ui_amplArc, 90);
    lv_obj_set_x(ui_amplArc, 35);
    lv_obj_set_y(ui_amplArc, 52);
    lv_obj_set_align(ui_amplArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_amplArc, 0, 3300);
    lv_arc_set_value(ui_amplArc, 0);

    lv_obj_set_style_arc_color(ui_amplArc, lv_color_hex(0x31C294), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_amplArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_amplArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_amplArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_amplArc, lv_color_hex(0x31C294), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_amplArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_amplArc, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_amplArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_amplArc, 255, LV_PART_KNOB | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_amplArc, 2, LV_PART_KNOB | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_amplArc, 3, LV_PART_KNOB | LV_STATE_FOCUS_KEY);

    ui_amplLabel = lv_label_create(ui_amplArc);
    lv_obj_set_width(ui_amplLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_amplLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_amplLabel, -30);
    lv_obj_set_y(ui_amplLabel, 0);
    lv_obj_set_align(ui_amplLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_amplLabel, "");
    lv_obj_set_style_text_color(ui_amplLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_amplLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mVLabel = lv_label_create(ui_amplArc);
    lv_obj_set_width(ui_mVLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mVLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mVLabel, -29);
    lv_obj_set_y(ui_mVLabel, 19);
    lv_obj_set_align(ui_mVLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mVLabel, "mV");
    lv_obj_set_style_text_color(ui_mVLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mVLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startButton = lv_btn_create(ui_functiongenscr);
    lv_obj_set_width(ui_startButton, 55);
    lv_obj_set_height(ui_startButton, 55);
    lv_obj_set_x(ui_startButton, 107);
    lv_obj_set_y(ui_startButton, 0);
    lv_obj_set_align(ui_startButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_startButton, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_startButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_startButton, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_startButton, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_startButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_startButton, 50, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_startButton, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_startButton, lv_color_hex(0x40534D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_startButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_startButton, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_startButton, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Image6 = lv_img_create(ui_startButton);
    lv_img_set_src(ui_Image6, &ui_img_1091903730);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, 1);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StartSignalLabel1 = lv_label_create(ui_functiongenscr);
    lv_obj_set_width(ui_StartSignalLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartSignalLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartSignalLabel1, 107);
    lv_obj_set_y(ui_StartSignalLabel1, -38);
    lv_obj_set_align(ui_StartSignalLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartSignalLabel1, "START");
    lv_obj_set_style_text_color(ui_StartSignalLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartSignalLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StartSignalLabel1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DutyCycleLabel = lv_label_create(ui_functiongenscr);
    lv_obj_set_width(ui_DutyCycleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DutyCycleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DutyCycleLabel, 3);
    lv_obj_set_y(ui_DutyCycleLabel, -63);
    lv_obj_set_align(ui_DutyCycleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DutyCycleLabel, "Duty cycle:");
    lv_obj_set_style_text_color(ui_DutyCycleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DutyCycleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DutyCycleLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dutyCycleDropdown = lv_dropdown_create(ui_functiongenscr);
    lv_dropdown_set_options(ui_dutyCycleDropdown,
                            "0%\n5%\n10%\n15%\n20%\n25%\n30%\n35%\n40%\n45%\n50%\n55%\n60%\n65%\n70%\n75%\n80%\n85%\n90%\n95%\n100%\n");
    lv_obj_set_width(ui_dutyCycleDropdown, 64);
    lv_obj_set_height(ui_dutyCycleDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dutyCycleDropdown, 6);
    lv_obj_set_y(ui_dutyCycleDropdown, -35);
    lv_obj_set_align(ui_dutyCycleDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dutyCycleDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_dutyCycleDropdown, lv_color_hex(0xF9F7F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dutyCycleDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_dutyCycleDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_dutyCycleDropdown, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_dutyCycleDropdown, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_dutyCycleDropdown, 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_dutyCycleDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_dutyCycleDropdown, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_dutyCycleDropdown, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_dutyCycleDropdown, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_text_color(ui_dutyCycleDropdown, lv_color_hex(0x202829), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dutyCycleDropdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_dutyCycleDropdown), lv_color_hex(0xC2C3C5),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_dutyCycleDropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_dutyCycleDropdown), lv_color_hex(0x31C294),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_dutyCycleDropdown), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_functiongenscr);
    lv_obj_set_width(ui_Panel3, 63);
    lv_obj_set_height(ui_Panel3, 48);
    lv_obj_set_x(ui_Panel3, 119);
    lv_obj_set_y(ui_Panel3, -104);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humText2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_humText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humText2, 6);
    lv_obj_set_y(ui_humText2, 9);
    lv_obj_set_align(ui_humText2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_humText2, "41.03 %");
    lv_obj_set_style_text_color(ui_humText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humText2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempText2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_tempText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempText2, 9);
    lv_obj_set_y(ui_tempText2, -8);
    lv_obj_set_align(ui_tempText2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_tempText2, "30°C");
    lv_obj_set_style_text_color(ui_tempText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempText2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deviceTooHotLabel2 = lv_label_create(ui_functiongenscr);
    lv_obj_set_width(ui_deviceTooHotLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deviceTooHotLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deviceTooHotLabel2, -1);
    lv_obj_set_y(ui_deviceTooHotLabel2, 4);
    lv_obj_set_align(ui_deviceTooHotLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deviceTooHotLabel2, "Device got too hot!\nShutting down ...");
    lv_obj_set_style_text_color(ui_deviceTooHotLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deviceTooHotLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_deviceTooHotLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deviceTooHotLabel2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_deviceTooHotLabel2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_deviceTooHotLabel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_deviceTooHotLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_deviceTooHotLabel2, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_deviceTooHotLabel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_deviceTooHotLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_deviceTooHotLabel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_deviceTooHotLabel2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_deviceTooHotLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_savePresetBtn = lv_btn_create(ui_functiongenscr);
    lv_obj_set_width(ui_savePresetBtn, 66);
    lv_obj_set_height(ui_savePresetBtn, 25);
    lv_obj_set_x(ui_savePresetBtn, 108);
    lv_obj_set_y(ui_savePresetBtn, 61);
    lv_obj_set_align(ui_savePresetBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_savePresetBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_savePresetBtn, lv_color_hex(0x4A6962), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_savePresetBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_savePresetBtn, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_savePresetBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_savePresetBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_savePresetBtn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_savePresetBtn, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_savePresetBtn, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label10 = lv_label_create(ui_savePresetBtn);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Save Preset");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_presetDropdown = lv_dropdown_create(ui_functiongenscr);
    lv_dropdown_set_dir(ui_presetDropdown, LV_DIR_TOP);
    lv_dropdown_set_options(ui_presetDropdown, "1\n2\n3\n4\n5");
    lv_obj_set_width(ui_presetDropdown, 42);
    lv_obj_set_height(ui_presetDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_presetDropdown, 108);
    lv_obj_set_y(ui_presetDropdown, 93);
    lv_obj_set_align(ui_presetDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_presetDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_presetDropdown, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_presetDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_presetDropdown, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_presetDropdown, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_presetDropdown, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_set_style_text_color(ui_presetDropdown, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_presetDropdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_presetDropdown, &lv_font_montserrat_10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_presetDropdown), LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_presetDropdown), &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_presetDropdown), lv_color_hex(0xC9C9C9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_presetDropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_functiongenscr);
    lv_img_set_src(ui_Image7, &ui_img_humidity_15px_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image7, 100);
    lv_obj_set_y(ui_Image7, -94);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_functiongenscr);
    lv_img_set_src(ui_Image3, &ui_img_temp_15px_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image3, 98);
    lv_obj_set_y(ui_Image3, -111);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_backBtn2, ui_event_backBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_signalTypeDropdown, ui_event_signalTypeDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_freqarc1, ui_event_freqarc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_amplArc, ui_event_amplArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_startButton, ui_event_startButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dutyCycleDropdown, ui_event_dutyCycleDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_savePresetBtn, ui_event_savePresetBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_presetDropdown, ui_event_presetDropdown, LV_EVENT_ALL, NULL);

}
