// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#include "../ui.h"

void ui_homescr_screen_init(void)
{
    ui_homescr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_homescr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homescr, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homescr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_homescr, lv_color_hex(0x202C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_homescr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_homescr, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_homescr);
    lv_img_set_src(ui_Image14, &ui_img_1501662095);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image14, -59);
    lv_obj_set_y(ui_Image14, 35);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fngen1 = lv_btn_create(ui_homescr);
    lv_obj_set_width(ui_fngen1, 200);
    lv_obj_set_height(ui_fngen1, 50);
    lv_obj_set_x(ui_fngen1, 42);
    lv_obj_set_y(ui_fngen1, 63);
    lv_obj_set_align(ui_fngen1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_fngen1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fngen1, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fngen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_fngen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_fngen1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_fngen1, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_fngen1, 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_fngen1, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_fngen1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_fngen1, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_fngen1, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_functiongen1 = lv_label_create(ui_fngen1);
    lv_obj_set_width(ui_functiongen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_functiongen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_functiongen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_functiongen1, "FUNCTION GENERATOR");

    ui_oscbutton1 = lv_btn_create(ui_homescr);
    lv_obj_set_width(ui_oscbutton1, 198);
    lv_obj_set_height(ui_oscbutton1, 50);
    lv_obj_set_x(ui_oscbutton1, 43);
    lv_obj_set_y(ui_oscbutton1, 4);
    lv_obj_set_align(ui_oscbutton1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_oscbutton1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oscbutton1, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oscbutton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_oscbutton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_oscbutton1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_oscbutton1, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_oscbutton1, 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_oscbutton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_oscbutton1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_oscbutton1, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_oscbutton1, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_oscilloscope1 = lv_label_create(ui_oscbutton1);
    lv_obj_set_width(ui_oscilloscope1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oscilloscope1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_oscilloscope1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_oscilloscope1, "OSCILLOSCOPE");
    lv_obj_add_state(ui_oscilloscope1, LV_STATE_PRESSED);       /// States
    lv_obj_set_style_text_color(ui_oscilloscope1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oscilloscope1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_homescr);
    lv_img_set_src(ui_Image8, &ui_img_bl_logo_light_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image8, -90);
    lv_obj_set_y(ui_Image8, -86);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_homescr);
    lv_obj_set_width(ui_Panel1, 67);
    lv_obj_set_height(ui_Panel1, 48);
    lv_obj_set_x(ui_Panel1, 113);
    lv_obj_set_y(ui_Panel1, -87);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x4D6861), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x202C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humText = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_humText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humText, 6);
    lv_obj_set_y(ui_humText, 9);
    lv_obj_set_align(ui_humText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_humText, "41.03%");
    lv_obj_set_style_text_color(ui_humText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempText = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_tempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempText, 9);
    lv_obj_set_y(ui_tempText, -8);
    lv_obj_set_align(ui_tempText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_tempText, "30.05°C");
    lv_obj_set_style_text_color(ui_tempText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image11, &ui_img_temp_15px_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image11, -21);
    lv_obj_set_y(ui_Image11, -8);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image12, &ui_img_humidity_15px_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image12, -20);
    lv_obj_set_y(ui_Image12, 9);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_deviceTooHotLabel1 = lv_label_create(ui_homescr);
    lv_obj_set_width(ui_deviceTooHotLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deviceTooHotLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deviceTooHotLabel1, -1);
    lv_obj_set_y(ui_deviceTooHotLabel1, 4);
    lv_obj_set_align(ui_deviceTooHotLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deviceTooHotLabel1, "Device got too hot!\nShutting down ...");
    lv_obj_set_style_text_color(ui_deviceTooHotLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deviceTooHotLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_deviceTooHotLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deviceTooHotLabel1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_deviceTooHotLabel1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_deviceTooHotLabel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_deviceTooHotLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_deviceTooHotLabel1, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_deviceTooHotLabel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_deviceTooHotLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_deviceTooHotLabel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_deviceTooHotLabel1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_deviceTooHotLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBtn = lv_btn_create(ui_homescr);
    lv_obj_set_width(ui_wifiBtn, 35);
    lv_obj_set_height(ui_wifiBtn, 35);
    lv_obj_set_x(ui_wifiBtn, 52);
    lv_obj_set_y(ui_wifiBtn, -87);
    lv_obj_set_align(ui_wifiBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_wifiBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiBtn, lv_color_hex(0x4A6962), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiBtn, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_wifiBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_wifiBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_wifiBtn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_wifiBtn, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_wifiBtn, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Image17 = lv_img_create(ui_wifiBtn);
    lv_img_set_src(ui_Image17, &ui_img_wifi_iconmini_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image17, 0);
    lv_obj_set_y(ui_Image17, 1);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image17, 135);

    lv_obj_add_event_cb(ui_fngen1, ui_event_fngen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oscbutton1, ui_event_oscbutton1, LV_EVENT_ALL, NULL);

}
