// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#include "../ui.h"

void ui_oscilloscopescr_screen_init(void)
{
    ui_oscilloscopescr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_oscilloscopescr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_oscilloscopescr, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oscilloscopescr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_oscilloscopescr, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_oscilloscopescr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_oscilloscopescr, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn = lv_btn_create(ui_oscilloscopescr);
    lv_obj_set_width(ui_backbtn, 31);
    lv_obj_set_height(ui_backbtn, 26);
    lv_obj_set_x(ui_backbtn, -132);
    lv_obj_set_y(ui_backbtn, -94);
    lv_obj_set_align(ui_backbtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_backbtn, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_backbtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_backbtn, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_backbtn, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_backbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_backbtn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_backbtn, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_backbtn, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Image4 = lv_img_create(ui_backbtn);
    lv_img_set_src(ui_Image4, &ui_img_653708034);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 100);

    ui_Panel4 = lv_obj_create(ui_oscilloscopescr);
    lv_obj_set_width(ui_Panel4, 63);
    lv_obj_set_height(ui_Panel4, 48);
    lv_obj_set_x(ui_Panel4, 118);
    lv_obj_set_y(ui_Panel4, -103);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humText3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_humText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humText3, 6);
    lv_obj_set_y(ui_humText3, 9);
    lv_obj_set_align(ui_humText3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_humText3, "41.03 %");
    lv_obj_set_style_text_color(ui_humText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humText3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempText3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_tempText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempText3, 9);
    lv_obj_set_y(ui_tempText3, -8);
    lv_obj_set_align(ui_tempText3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_tempText3, "30°C");
    lv_obj_set_style_text_color(ui_tempText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempText3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_oscilloscopescr);
    lv_img_set_src(ui_Image9, &ui_img_humidity_15px_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image9, 100);
    lv_obj_set_y(ui_Image9, -94);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_oscilloscopescr);
    lv_img_set_src(ui_Image10, &ui_img_temp_15px_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image10, 98);
    lv_obj_set_y(ui_Image10, -112);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_oscconfigPanel = lv_obj_create(ui_oscilloscopescr);
    lv_obj_set_width(ui_oscconfigPanel, 193);
    lv_obj_set_height(ui_oscconfigPanel, 58);
    lv_obj_set_x(ui_oscconfigPanel, -14);
    lv_obj_set_y(ui_oscconfigPanel, -102);
    lv_obj_set_align(ui_oscconfigPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_oscconfigPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_oscconfigPanel, lv_color_hex(0x31C294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oscconfigPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_oscconfigPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_oscconfigPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_oscconfigPanel, lv_color_hex(0xBFBFBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_oscconfigPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_oscconfigPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_oscconfigPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ch1Btn = lv_btn_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_ch1Btn, 35);
    lv_obj_set_height(ui_ch1Btn, 35);
    lv_obj_set_x(ui_ch1Btn, -76);
    lv_obj_set_y(ui_ch1Btn, 7);
    lv_obj_set_align(ui_ch1Btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ch1Btn, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ch1Btn, lv_color_hex(0x7B8183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ch1Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ch1Btn, lv_color_hex(0x9A9A9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ch1Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ch1Btn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ch1Btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ch1Btn, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ch1Btn, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ch1Btn, lv_color_hex(0xFF9AFE), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ch1Btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_ch1Btn, 2, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_ch1Btn, 2, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_ch1Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_ch1Btn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_ch1Btn, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_ch1Btn, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_color(ui_ch1Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_ch1Btn, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_ch1Btn, 2, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_ch1Btn, 3, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUS_KEY);

    ui_Label4 = lv_label_create(ui_ch1Btn);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "CH1");

    ui_ch1Btn1 = lv_btn_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_ch1Btn1, 35);
    lv_obj_set_height(ui_ch1Btn1, 35);
    lv_obj_set_x(ui_ch1Btn1, -36);
    lv_obj_set_y(ui_ch1Btn1, 7);
    lv_obj_set_align(ui_ch1Btn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ch1Btn1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ch1Btn1, lv_color_hex(0x7B8183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ch1Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ch1Btn1, lv_color_hex(0x929294), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ch1Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ch1Btn1, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ch1Btn1, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ch1Btn1, lv_color_hex(0x5BC6CA), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ch1Btn1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_ch1Btn1, 2, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_ch1Btn1, 2, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_ch1Btn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_ch1Btn1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_ch1Btn1, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_ch1Btn1, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label2 = lv_label_create(ui_ch1Btn1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "CH2");

    ui_divms10 = lv_btn_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_divms10, 46);
    lv_obj_set_height(ui_divms10, 15);
    lv_obj_set_x(ui_divms10, 15);
    lv_obj_set_y(ui_divms10, 0);
    lv_obj_set_align(ui_divms10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_divms10, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_divms10, lv_color_hex(0x7B8183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_divms10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_divms10, lv_color_hex(0xBFBFBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_divms10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_divms10, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_divms10, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label5 = lv_label_create(ui_divms10);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "10 ms");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_divms1 = lv_btn_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_divms1, 46);
    lv_obj_set_height(ui_divms1, 15);
    lv_obj_set_x(ui_divms1, 15);
    lv_obj_set_y(ui_divms1, 15);
    lv_obj_set_align(ui_divms1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_divms1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_divms1, lv_color_hex(0x7B8183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_divms1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_divms1, lv_color_hex(0xBFBFBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_divms1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_divms1, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_divms1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_divms1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "1 ms");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_div500mV = lv_btn_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_div500mV, 46);
    lv_obj_set_height(ui_div500mV, 15);
    lv_obj_set_x(ui_div500mV, 68);
    lv_obj_set_y(ui_div500mV, 0);
    lv_obj_set_align(ui_div500mV, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_div500mV, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_div500mV, lv_color_hex(0x7B8183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_div500mV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_div500mV, lv_color_hex(0xBFBFBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_div500mV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_div500mV, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_div500mV, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label6 = lv_label_create(ui_div500mV);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "500 mV");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_divmV100 = lv_btn_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_divmV100, 46);
    lv_obj_set_height(ui_divmV100, 15);
    lv_obj_set_x(ui_divmV100, 68);
    lv_obj_set_y(ui_divmV100, 15);
    lv_obj_set_align(ui_divmV100, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_divmV100, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_divmV100, lv_color_hex(0x7B8183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_divmV100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_divmV100, lv_color_hex(0xBFBFBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_divmV100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_divmV100, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_divmV100, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label7 = lv_label_create(ui_divmV100);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "100 mV");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 15);
    lv_obj_set_y(ui_Label8, -13);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "divX");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 68);
    lv_obj_set_y(ui_Label9, -13);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "divY");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_togglemsBtn = lv_btn_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_togglemsBtn, 47);
    lv_obj_set_height(ui_togglemsBtn, 32);
    lv_obj_set_x(ui_togglemsBtn, 15);
    lv_obj_set_y(ui_togglemsBtn, 8);
    lv_obj_set_align(ui_togglemsBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_togglemsBtn, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_togglemsBtn, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_togglemsBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_togglemsBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_togglemsBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_togglemsBtn, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_togglemsBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_togglemsBtn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_togglemsBtn, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_togglemsBtn, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_togglemVBtn = lv_btn_create(ui_oscconfigPanel);
    lv_obj_set_width(ui_togglemVBtn, 47);
    lv_obj_set_height(ui_togglemVBtn, 31);
    lv_obj_set_x(ui_togglemVBtn, 68);
    lv_obj_set_y(ui_togglemVBtn, 8);
    lv_obj_set_align(ui_togglemVBtn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_togglemVBtn, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_togglemVBtn, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_togglemVBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_togglemVBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_togglemVBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_togglemVBtn, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_togglemVBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(ui_togglemVBtn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(ui_togglemVBtn, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(ui_togglemVBtn, 3, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Chart2 = lv_chart_create(ui_oscilloscopescr);
    lv_obj_set_width(ui_Chart2, 296);
    lv_obj_set_height(ui_Chart2, 176);
    lv_obj_set_x(ui_Chart2, 0);
    lv_obj_set_y(ui_Chart2, 21);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart2, 200);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 3500);
    lv_chart_set_div_line_count(ui_Chart2, 8, 6);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 0, 0, 12, 3, false, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 8, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0x202829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart2, lv_color_hex(0xB6B6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0x31C294), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_Chart2, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_Chart2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_Chart2, 1, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Chart2, false, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_fngenonflagLabel = lv_label_create(ui_Chart2);
    lv_obj_set_width(ui_fngenonflagLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fngenonflagLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fngenonflagLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fngenonflagLabel, "Can't use oscilloscope while \nfunction generator is running!");
    lv_obj_set_style_text_color(ui_fngenonflagLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fngenonflagLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fngenonflagLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fngenonflagLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fngenonflagLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_fngenonflagLabel, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_fngenonflagLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_fngenonflagLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_fngenonflagLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_fngenonflagLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deviceTooHotLabel = lv_label_create(ui_oscilloscopescr);
    lv_obj_set_width(ui_deviceTooHotLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deviceTooHotLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_deviceTooHotLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deviceTooHotLabel, "Device got too hot!\nShutting down ...");
    lv_obj_set_style_text_color(ui_deviceTooHotLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deviceTooHotLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_deviceTooHotLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deviceTooHotLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_deviceTooHotLabel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_deviceTooHotLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_deviceTooHotLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_deviceTooHotLabel, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_deviceTooHotLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_deviceTooHotLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_deviceTooHotLabel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_deviceTooHotLabel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_deviceTooHotLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbtn, ui_event_backbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ch1Btn, ui_event_ch1Btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ch1Btn1, ui_event_ch1Btn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_togglemsBtn, ui_event_togglemsBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_togglemVBtn, ui_event_togglemVBtn, LV_EVENT_ALL, NULL);

}
