// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_homescr
void ui_homescr_screen_init(void);
lv_obj_t * ui_homescr;
lv_obj_t * ui_Image14;
void ui_event_fngen1(lv_event_t * e);
lv_obj_t * ui_fngen1;
lv_obj_t * ui_functiongen1;
void ui_event_oscbutton1(lv_event_t * e);
lv_obj_t * ui_oscbutton1;
lv_obj_t * ui_oscilloscope1;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_humText;
lv_obj_t * ui_tempText;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image12;
lv_obj_t * ui_deviceTooHotLabel1;
lv_obj_t * ui_wifiBtn;
lv_obj_t * ui_Image17;


// SCREEN: ui_oscilloscopescr
void ui_oscilloscopescr_screen_init(void);
lv_obj_t * ui_oscilloscopescr;
void ui_event_backbtn(lv_event_t * e);
lv_obj_t * ui_backbtn;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_humText3;
lv_obj_t * ui_tempText3;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
lv_obj_t * ui_oscconfigPanel;
void ui_event_ch1Btn(lv_event_t * e);
lv_obj_t * ui_ch1Btn;
lv_obj_t * ui_Label4;
void ui_event_ch1Btn1(lv_event_t * e);
lv_obj_t * ui_ch1Btn1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_divms10;
lv_obj_t * ui_Label5;
lv_obj_t * ui_divms1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_div500mV;
lv_obj_t * ui_Label6;
lv_obj_t * ui_divmV100;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
void ui_event_togglemsBtn(lv_event_t * e);
lv_obj_t * ui_togglemsBtn;
void ui_event_togglemVBtn(lv_event_t * e);
lv_obj_t * ui_togglemVBtn;
lv_obj_t * ui_Chart2;
lv_obj_t * ui_fngenonflagLabel;
lv_obj_t * ui_deviceTooHotLabel;


// SCREEN: ui_functiongenscr
void ui_functiongenscr_screen_init(void);
lv_obj_t * ui_functiongenscr;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Label1;
void ui_event_backBtn2(lv_event_t * e);
lv_obj_t * ui_backBtn2;
lv_obj_t * ui_Image5;
void ui_event_signalTypeDropdown(lv_event_t * e);
lv_obj_t * ui_signalTypeDropdown;
lv_obj_t * ui_signalTypeLabel;
void ui_event_freqarc1(lv_event_t * e);
lv_obj_t * ui_freqarc1;
lv_obj_t * ui_freqLabel1;
lv_obj_t * ui_HzLabel;
void ui_event_amplArc(lv_event_t * e);
lv_obj_t * ui_amplArc;
lv_obj_t * ui_amplLabel;
lv_obj_t * ui_mVLabel;
void ui_event_startButton(lv_event_t * e);
lv_obj_t * ui_startButton;
lv_obj_t * ui_Image6;
lv_obj_t * ui_StartSignalLabel1;
lv_obj_t * ui_DutyCycleLabel;
void ui_event_dutyCycleDropdown(lv_event_t * e);
lv_obj_t * ui_dutyCycleDropdown;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_humText2;
lv_obj_t * ui_tempText2;
lv_obj_t * ui_deviceTooHotLabel2;
void ui_event_savePresetBtn(lv_event_t * e);
lv_obj_t * ui_savePresetBtn;
lv_obj_t * ui_Label10;
void ui_event_presetDropdown(lv_event_t * e);
lv_obj_t * ui_presetDropdown;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image3;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_fngen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_functiongenscr, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_functiongenscr_screen_init);
    }
}
void ui_event_oscbutton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_oscilloscopescr, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_oscilloscopescr_screen_init);
    }
}
void ui_event_backbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homescr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_homescr_screen_init);
    }
}
void ui_event_ch1Btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ch1_show(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ch1_hide(e);
    }
}
void ui_event_ch1Btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ch2_show(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ch2_hide(e);
    }
}
void ui_event_togglemsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_divms1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_divms10, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        set_div_10ms(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_divms1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_divms10, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        set_div_1ms(e);
    }
}
void ui_event_togglemVBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_divmV100, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_div500mV, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        set_div_500mV(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_divmV100, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_div500mV, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        set_div_100mV(e);
    }
}
void ui_event_backBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homescr, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_homescr_screen_init);
    }
}
void ui_event_signalTypeDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_signal_type_dropdown_cb(e);
    }
}
void ui_event_freqarc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_label_set_property(ui_freqLabel1, _UI_LABEL_PROPERTY_TEXT, "");
        _ui_arc_set_text_value(ui_freqLabel1, target, "", "");
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_UP) {
        _ui_arc_increment(ui_freqarc1, 50);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_DOWN) {
        _ui_arc_increment(ui_freqarc1, -50);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_freq_arc_cb(e);
    }
}
void ui_event_amplArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_label_set_property(ui_amplLabel, _UI_LABEL_PROPERTY_TEXT, "");
        _ui_arc_set_text_value(ui_amplLabel, target, "", "");
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_UP) {
        _ui_arc_increment(ui_amplArc, 50);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_DOWN) {
        _ui_arc_increment(ui_amplArc, -50);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_ampl_arc_cb(e);
    }
}
void ui_event_startButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ui_start_btn_checked_cb(e);
        _ui_opacity_set(ui_fngenonflagLabel, 255);
        _ui_label_set_property(ui_StartSignalLabel1, _UI_LABEL_PROPERTY_TEXT, "STOP");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        ui_start_btn_unchecked_cb(e);
        _ui_opacity_set(ui_fngenonflagLabel, 0);
        _ui_label_set_property(ui_StartSignalLabel1, _UI_LABEL_PROPERTY_TEXT, "START");
    }
}
void ui_event_dutyCycleDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_duty_cycle_dropdown_cb(e);
    }
}
void ui_event_savePresetBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_save_preset(e);
    }
}
void ui_event_presetDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_load_preset(e);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_opacity_set(ui_fngenonflagLabel, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_state_modify(ui_div500mV, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_divms10, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_ch1Btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_ch1Btn1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_togglemsBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_togglemVBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_togglemsBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        ui_init_preset(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_homescr_screen_init();
    ui_oscilloscopescr_screen_init();
    ui_functiongenscr_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_homescr);
}
