// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#ifndef _MASHINA_SQ_FN_GEN_SCREEN_ALMOST_WORK_UI_H
#define _MASHINA_SQ_FN_GEN_SCREEN_ALMOST_WORK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_homescr
void ui_homescr_screen_init(void);
extern lv_obj_t * ui_homescr;
extern lv_obj_t * ui_Image14;
void ui_event_fngen1(lv_event_t * e);
extern lv_obj_t * ui_fngen1;
extern lv_obj_t * ui_functiongen1;
void ui_event_oscbutton1(lv_event_t * e);
extern lv_obj_t * ui_oscbutton1;
extern lv_obj_t * ui_oscilloscope1;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_humText;
extern lv_obj_t * ui_tempText;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_deviceTooHotLabel1;
extern lv_obj_t * ui_wifiBtn;
extern lv_obj_t * ui_Image17;
// SCREEN: ui_oscilloscopescr
void ui_oscilloscopescr_screen_init(void);
extern lv_obj_t * ui_oscilloscopescr;
void ui_event_backbtn(lv_event_t * e);
extern lv_obj_t * ui_backbtn;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_humText3;
extern lv_obj_t * ui_tempText3;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_oscconfigPanel;
void ui_event_ch1Btn(lv_event_t * e);
extern lv_obj_t * ui_ch1Btn;
extern lv_obj_t * ui_Label4;
void ui_event_ch1Btn1(lv_event_t * e);
extern lv_obj_t * ui_ch1Btn1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_divms10;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_divms1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_div500mV;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_divmV100;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
void ui_event_togglemsBtn(lv_event_t * e);
extern lv_obj_t * ui_togglemsBtn;
void ui_event_togglemVBtn(lv_event_t * e);
extern lv_obj_t * ui_togglemVBtn;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_fngenonflagLabel;
extern lv_obj_t * ui_deviceTooHotLabel;
// SCREEN: ui_functiongenscr
void ui_functiongenscr_screen_init(void);
extern lv_obj_t * ui_functiongenscr;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label1;
void ui_event_backBtn2(lv_event_t * e);
extern lv_obj_t * ui_backBtn2;
extern lv_obj_t * ui_Image5;
void ui_event_signalTypeDropdown(lv_event_t * e);
extern lv_obj_t * ui_signalTypeDropdown;
extern lv_obj_t * ui_signalTypeLabel;
void ui_event_freqarc1(lv_event_t * e);
extern lv_obj_t * ui_freqarc1;
extern lv_obj_t * ui_freqLabel1;
extern lv_obj_t * ui_HzLabel;
void ui_event_amplArc(lv_event_t * e);
extern lv_obj_t * ui_amplArc;
extern lv_obj_t * ui_amplLabel;
extern lv_obj_t * ui_mVLabel;
void ui_event_startButton(lv_event_t * e);
extern lv_obj_t * ui_startButton;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_StartSignalLabel1;
extern lv_obj_t * ui_DutyCycleLabel;
void ui_event_dutyCycleDropdown(lv_event_t * e);
extern lv_obj_t * ui_dutyCycleDropdown;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_humText2;
extern lv_obj_t * ui_tempText2;
extern lv_obj_t * ui_deviceTooHotLabel2;
void ui_event_savePresetBtn(lv_event_t * e);
extern lv_obj_t * ui_savePresetBtn;
extern lv_obj_t * ui_Label10;
void ui_event_presetDropdown(lv_event_t * e);
extern lv_obj_t * ui_presetDropdown;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image3;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1501662095);    // assets/signalgenerator-svgrepo-com(1).png
LV_IMG_DECLARE(ui_img_bl_logo_light_png);    // assets/bl_logo_light.png
LV_IMG_DECLARE(ui_img_temp_15px_png);    // assets/temp_15px.png
LV_IMG_DECLARE(ui_img_humidity_15px_png);    // assets/humidity_15px.png
LV_IMG_DECLARE(ui_img_wifi_iconmini_png);    // assets/wifi_iconmini.png
LV_IMG_DECLARE(ui_img_653708034);    // assets/left_arrow(1).png
LV_IMG_DECLARE(ui_img_bl_logo_symbol_png);    // assets/bl_logo_symbol.png
LV_IMG_DECLARE(ui_img_1091903730);    // assets/play-xxl.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
