// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: mashina_sq_fn_gen_screen_almost_work

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_init_preset(lv_event_t * e);
void ch1_show(lv_event_t * e);
void ch1_hide(lv_event_t * e);
void ch2_show(lv_event_t * e);
void ch2_hide(lv_event_t * e);
void set_div_10ms(lv_event_t * e);
void set_div_1ms(lv_event_t * e);
void set_div_500mV(lv_event_t * e);
void set_div_100mV(lv_event_t * e);
void ui_signal_type_dropdown_cb(lv_event_t * e);
void ui_freq_arc_cb(lv_event_t * e);
void ui_ampl_arc_cb(lv_event_t * e);
void ui_start_btn_checked_cb(lv_event_t * e);
void ui_start_btn_unchecked_cb(lv_event_t * e);
void ui_duty_cycle_dropdown_cb(lv_event_t * e);
void ui_save_preset(lv_event_t * e);
void ui_load_preset(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
